name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies and Android SDK
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-dev git openjdk-17-jdk \
        build-essential zlib1g-dev libffi-dev libssl-dev \
        libsqlite3-dev libncurses5-dev libncursesw5-dev libreadline-dev \
        libbz2-dev libgdbm-dev liblzma-dev wget curl unzip
        pip install --upgrade pip setuptools wheel cython buildozer

        # Android SDK Command Line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip

        # Создаём директории заранее
        mkdir -p $HOME/android-sdk/cmdline-tools/tmp
        mkdir -p $HOME/android-sdk/cmdline-tools/latest

        # Распаковываем и переносим внутреннюю папку cmdline-tools в latest
        unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools/tmp
        mv $HOME/android-sdk/cmdline-tools/tmp/cmdline-tools $HOME/android-sdk/cmdline-tools/latest/
        rm -rf $HOME/android-sdk/cmdline-tools/tmp

        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH

        # Устанавливаем необходимые пакеты Android SDK
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build APK
      run: |
        # Экспортируем PATH прямо перед сборкой
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH
        buildozer android debug
      shell: bash

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: ./bin/*.apk
